const NETWORKS = {
	5: {
		BRIDGE_CONTRACT_ADDRESS: "0x8fa6cd9a275506d719c434335c0c9ffd15e05a87",
		MAIN_TOKEN_ADDRESS: "0x97d9b397189e8b771ffac3cb04cf26c780a93431",
		RELAYER: "5EcAFwVcBo8s2D3ZSTnx2sq49wVDF3rc1yGJMx5nRp2GsK62",
		GATEWAY: "https://testnet.gateway.aventus.io/",
		EXPLORER_TX_URL: "https://explorer.testnet.aventus.io/transaction/",
		ENVIRONMENT_NAME: "AvN Testnet",
		COMPANY_NAME: "Aventus",
		ETHERSCAN_TX_LINK: "https://goerli.etherscan.io/tx/",
		ETHERSCAN_TOKEN_LINK: "https://goerli.etherscan.io/token/",
		EVM_NETWORK_NAME: "Goerli Testnet",
		NETWORK_ID: 5,
		ALTERNATE_NETWORK_URL: "https://lift.aventus.io/",
		ALTERNATE_NETWORK_NAME: "Mainnet",
		SUPPORTED_TOKENS: {
			MAIN_TOKEN: { value: "AVT", position: "1" },
			ERC20: { value: "ERC20", position: "0" },
			ERC777: { value: "ERC777", position: "0" },
			ETH: { value: "ETH", position: "0" },
		},
	},
	73799: {
		BRIDGE_CONTRACT_ADDRESS: "0x1D9296366630fA48e74A72AdCeF52F6A7C31cB9E",
		MAIN_TOKEN_ADDRESS: "", //not useful for this network
		RELAYER: "5EcAFwVcBo8s2D3ZSTnx2sq49wVDF3rc1yGJMx5nRp2GsK62",
		ETHERSCAN_TOKEN_LINK: "https://volta-explorer.energyweb.org/address/",
		ETHERSCAN_TX_LINK: "https://volta-explorer.energyweb.org/tx/",
		ALTERNATE_NETWORK_URL: "https://lift.mainnet.energywebx.com/",
		ENVIRONMENT_NAME: "EW Testnet",
		EVM_NETWORK_NAME: "Volta EVM Testnet",
		COMPANY_NAME: "Energy Web",
		NETWORK_ID: 73799,
		ALTERNATE_NETWORK_NAME: "Mainnet",
		SUPPORTED_TOKENS: {
			NATIVE: { value: "EWT", position: "1" },
			// MAIN_TOKEN: { value: "AVT", position: "0" },
			ERC20: { value: "ERC20", position: "0" },
			ERC777: { value: "ERC777", position: "0" },
		},
	},
	246: {
		BRIDGE_CONTRACT_ADDRESS: "0x1D9296366630fA48e74A72AdCeF52F6A7C31cB9E",
		MAIN_TOKEN_ADDRESS: "",
		RELAYER: "5EcAFwVcBo8s2D3ZSTnx2sq49wVDF3rc1yGJMx5nRp2GsK62",
		ENVIRONMENT_NAME: "EW Testnet",
		EVM_NETWORK_NAME: "Energy Web EVM Mainnet",
		COMPANY_NAME: "Energy Web",
		ETHERSCAN_TOKEN_LINK: "https://volta-explorer.energyweb.org/address/",
		ETHERSCAN_TX_LINK: "https://volta-explorer.energyweb.org/tx/",
		NETWORK_ID: 246,
		ALTERNATE_NETWORK_URL: "https://lift.testnet.energywebx.com/",
		ALTERNATE_NETWORK_NAME: "Testnet",
		SUPPORTED_TOKENS: {
			NATIVE: { value: "EWT", position: "1" },
			// MAIN_TOKEN: { value: "AVT", position: "0" },
			ERC20: { value: "ERC20", position: "0" },
			ERC777: { value: "ERC777", position: "0" },
		},
	},
	1: {
		MAIN_TOKEN_ADDRESS: "0x0d88eD6E74bbFD96B831231638b66C05571e824F",
		BRIDGE_CONTRACT_ADDRESS: "0xf05df39f745a240fb133cc4a11e42467fab10f1f",
		GATEWAY: "https://mainnet.gateway.aventus.io/",
		RELAYER: "5Gh6CfQUNDzsk7TQ8Tt8SR9h8mAQXpEpeZjNKFoVxYWqLAEB",
		EXPLORER_TX_URL: "https://explorer.mainnet.aventus.io/transaction/",
		ETHERSCAN_TOKEN_LINK: "https://etherscan.io/token/",
		ETHERSCAN_TX_LINK: "https://etherscan.io/tx/",
		EVM_NETWORK_NAME: "Ethereum Mainnet",
		ENVIRONMENT_NAME: "AvN Mainnet",
		ALTERNATE_NETWORK_URL: "https://lift.testnet.aventus.io/",
		ALTERNATE_NETWORK_NAME: "Testnet",
		COMPANY_NAME: "Aventus",
		SUPPORTED_TOKENS: {
			MAIN_TOKEN: { value: "AVT", position: "1" },
			ERC20: { value: "ERC20", position: "0" },
			ERC777: { value: "ERC777", position: "0" },
			ETH: { value: "ETH", position: "0" },
		},
		NETWORK_ID: 1,
	},
};

var appConfig = {
	NETWORK: NETWORKS[1],
};
