var appConfig = {
  // Aventus lowering dapp MAINNET config
  ALTERNATE_NETWORK_URL: 'https://lower.voucherledger.com/',
  ALTERNATE_NETWORK_NAME: 'Mainnet',
  BRIDGE_CONTRACT_ADDRESS: '0xb7480b6e5223beb2cdc8f6338ccc831b69453ab3',
  BUTTON_COLOR: '#5100FF',
  COMPANY_NAME: 'Enigmatic Smiles',
  COMPANY_URL: 'https://www.enigmaticsmile.com/',
  COMPANY_SUPPORT_URL: 'https://www.enigmaticsmile.com/contact',
  COMPANY_NAME_WITH_UNDERSCORE: 'VOW',
  ENVIRONMENT_NAME: 'Testnet',
  ETHERSCAN_TX_LINK: 'https://sepolia.etherscan.io/tx/',
  ETHERSCAN_TOKEN_LINK: 'https://sepolia.etherscan.io/token/',
  EVM_NETWORK_NAME: 'Sepolia',
  EXPLORER_TX_URL: 'https://explorer.testnet.voucherledger.com/transaction/',
  GATEWAY: 'https://gateway.testnet.voucherledger.com/',
  LOWER_DURATION: '24 hours',
  NETWORK_ID: 11155111,
  PRIMARY_TOKEN_ADDRESS: '0xbFaffD8001493Dfeb51C26748d2AfF53C2984190',
  PRIMARY_TOKEN: 'VOW',
  RELAYER: '5HGqmPWVyR6krAAgjy98t2aPmgw3ugZgKFzWoyKL9R4TQxA6',
  SUPPORTS_ENTERPRISE_USERS: true,
  SHOW_BALANCE_PAGE: true,
  SUPPORTED_TOKENS: {
    MAIN_TOKEN: { value: 'VOW', position: '1' },
    ERC20: { value: 'ERC20', position: '0' },
    ERC777: { value: 'ERC777', position: '0' },
    NATIVE: { value: 'ETH', position: '0' },
  },
}
